"""
HEKATE PRIME — Tam 78 Kart Tarot Destesi
Major Arcana (22) + Minor Arcana (56)
Her kart: düz + ters anlam, anahtar kelimeler, element, sayı
"""

# ── MAJOR ARCANA (22 kart) ────────────────────────────────────
MAJOR_ARCANA = [
    {"id": 0,  "suit": "major", "name": "The Fool",          "tr": "Deli",            "icon": "🌪️",
     "element": "Hava", "planet": "Uranüs",
     "keywords": "yeni başlangıçlar, saf cesaret, özgürlük, macera",
     "upright":  "Yeni bir yolculuğun başlangıcı. Korkusuzca atla — evren seni tutar. Saf enerji ve sonsuz potansiyel.",
     "reversed": "Dikkatsizlik, körü körüne atlamak, olgunlaşmamış kararlar. Dur ve düşün."},
    {"id": 1,  "suit": "major", "name": "The Magician",      "tr": "Büyücü",          "icon": "⚡",
     "element": "Ateş", "planet": "Merkür",
     "keywords": "irade, yaratıcı güç, manifestasyon, beceri",
     "upright":  "Elindeki araçları kullan. Gerçekleştirme gücün zirveye ulaştı. İstek + eylem = sonuç.",
     "reversed": "Manipülasyon, yanıltma, yeteneklerin boşa harcanması. Niyetini sorgula."},
    {"id": 2,  "suit": "major", "name": "The High Priestess","tr": "Yüksek Rahibe",   "icon": "🌙",
     "element": "Su", "planet": "Ay",
     "keywords": "sezgi, gizem, bilinçaltı, içsel bilgi",
     "upright":  "Sessizliğe çekil. Cevap içinde. Rüyalarına, sezgine, sessiz sese kulak ver.",
     "reversed": "Bastırılmış sezgi, sırların ifşası, içsel sesin görmezden gelinmesi."},
    {"id": 3,  "suit": "major", "name": "The Empress",       "tr": "İmparatoriçe",   "icon": "🌺",
     "element": "Toprak", "planet": "Venüs",
     "keywords": "bereket, yaratıcılık, doğa, annelik, bolluk",
     "upright":  "Doğurganlık ve yaratım enerjisi aktif. Besle, büyüt, üret. Doğayla bağlan.",
     "reversed": "Yaratıcı blok, aşırı koruyuculuk, bağımlılık, ihmal."},
    {"id": 4,  "suit": "major", "name": "The Emperor",       "tr": "İmparator",      "icon": "♦️",
     "element": "Ateş", "planet": "Mars",
     "keywords": "otorite, yapı, liderlik, düzen, disiplin",
     "upright":  "Sınırlarını koy. Düzeni sağla. Liderlik sorumluluğunu al.",
     "reversed": "Tiranlık, katılık, aşırı kontrol, zayıf liderlik."},
    {"id": 5,  "suit": "major", "name": "The Hierophant",    "tr": "Başrahip",       "icon": "🏛️",
     "element": "Toprak", "planet": "Venüs",
     "keywords": "gelenek, manevi rehberlik, kurumlar, inanç",
     "upright":  "Bir öğretmenden ya da geleneğin bilgeliğinden öğren. Ruhsal rehberlik zamanı.",
     "reversed": "Dogmatizm, körü körüne itaat, kurumsal baskı, yenilikçi arayış."},
    {"id": 6,  "suit": "major", "name": "The Lovers",        "tr": "Aşıklar",        "icon": "💞",
     "element": "Hava", "planet": "İkizler",
     "keywords": "ilişkiler, seçimler, uyum, değerler, birlik",
     "upright":  "Derin bir bağ ya da kritik bir seçim. Kalbinin rehberliğine güven.",
     "reversed": "Uyumsuzluk, yanlış seçimler, iletişim kopukluğu, değer çatışması."},
    {"id": 7,  "suit": "major", "name": "The Chariot",       "tr": "Savaş Arabası",  "icon": "🏇",
     "element": "Su", "planet": "Yengeç",
     "keywords": "irade gücü, zafer, kontrol, kararlılık, seyahat",
     "upright":  "Zıt güçleri kontrol et ve ilerle. Zafer irade ile gelir.",
     "reversed": "Kontrol kaybı, saldırganlık, yönden sapma, başarısız güdüm."},
    {"id": 8,  "suit": "major", "name": "Strength",          "tr": "Güç",             "icon": "🦁",
     "element": "Ateş", "planet": "Güneş",
     "keywords": "iç güç, sabır, cesaret, şefkat, dayanıklılık",
     "upright":  "Aslan değil; sabır ve şefkat en büyük güçtür. İç kaosu yumuşatarak yönet.",
     "reversed": "Öz şüphe, zayıflık, korku, bastırılmış içgüdüler."},
    {"id": 9,  "suit": "major", "name": "The Hermit",        "tr": "Münzevi",         "icon": "🕯️",
     "element": "Toprak", "planet": "Merkür",
     "keywords": "iç arayış, yalnızlık, bilgelik, rehberlik, içe çekilme",
     "upright":  "Geri çekil ve içine bak. Yanıtlar sessizlikte. Bir mentörün rehberliği geliyor.",
     "reversed": "İzolasyon, yalnızlık, geri çekilme korkusu, reddedilen rehberlik."},
    {"id": 10, "suit": "major", "name": "Wheel of Fortune",  "tr": "Kader Çarkı",    "icon": "🎡",
     "element": "Ateş", "planet": "Jüpiter",
     "keywords": "döngüler, şans, kader, dönüm noktası, değişim",
     "upright":  "Kader dönüyor. Değişime direnmek yerine onunla dans et.",
     "reversed": "Şanssızlık, direniş, döngüyü kıramama, talihsiz zamanlama."},
    {"id": 11, "suit": "major", "name": "Justice",            "tr": "Adalet",          "icon": "⚖️",
     "element": "Hava", "planet": "Terazi",
     "keywords": "denge, hakikat, sonuçlar, hesap verebilirlik, hukuk",
     "upright":  "Sonuçlar geliyor. Yaptığının karşılığını alacaksın — iyi ya da kötü.",
     "reversed": "Haksızlık, sorumsuzluk, yanlı kararlar, kaçınılan hesap."},
    {"id": 12, "suit": "major", "name": "The Hanged Man",    "tr": "Asılan Adam",    "icon": "🔄",
     "element": "Su", "planet": "Neptün",
     "keywords": "bekleme, farklı bakış açısı, fedakarlık, askıda kalma",
     "upright":  "Dur. Bekle. Başka bir açıdan bak. Bu bekleme boşa değil — dönüşüm hazırlığı.",
     "reversed": "Direniş, gereksiz fedakarlık, zaman kaybı, askıda kalmayı reddetme."},
    {"id": 13, "suit": "major", "name": "Death",              "tr": "Ölüm",            "icon": "🌑",
     "element": "Su", "planet": "Akrep",
     "keywords": "dönüşüm, son ve başlangıç, değişim, geçiş, bırakma",
     "upright":  "Bir şey bitiyor — bu iyi. Yeni başlamak için eski ölmeli. Direnmek acıyı uzatır.",
     "reversed": "Değişime direnç, durgunluk, ölüm korkusu, bırakamama."},
    {"id": 14, "suit": "major", "name": "Temperance",         "tr": "Denge",           "icon": "🌊",
     "element": "Ateş", "planet": "Yay",
     "keywords": "ölçülülük, sabır, akış, uyum, sentez",
     "upright":  "İki karşıtı harmanlıyorsun. Sabır ve ölçülülük zamanı. Aşırılıklardan kaçın.",
     "reversed": "Aşırılık, sabırsızlık, dengesizlik, çatışan güçler."},
    {"id": 15, "suit": "major", "name": "The Devil",          "tr": "Şeytan",          "icon": "🔗",
     "element": "Toprak", "planet": "Oğlak",
     "keywords": "bağlar, gölge benlik, bağımlılık, maddi dünya, kısıtlama",
     "upright":  "Ne seni tutuyor? Zincirler düşündüğünden daha gevşek. Gölgenle yüzleş.",
     "reversed": "Özgürleşme, bağımlılığı kırma, sınırlamaların farkındalığı."},
    {"id": 16, "suit": "major", "name": "The Tower",          "tr": "Kule",            "icon": "⚡",
     "element": "Ateş", "planet": "Mars",
     "keywords": "ani değişim, yıkım, özgürleşme, kaos, aydınlanma",
     "upright":  "Yıkım kaçınılmaz — ama yıkılan şey zaten çürüktü. Enkaz üstüne daha sağlam kur.",
     "reversed": "Kaçınılan felaket, gecikmiş yıkım, değişime direniş."},
    {"id": 17, "suit": "major", "name": "The Star",           "tr": "Yıldız",          "icon": "⭐",
     "element": "Hava", "planet": "Kova",
     "keywords": "umut, ilham, şifa, rehberlik, yenilenme",
     "upright":  "Karanlığın ardından ışık. Umudu bırakma. Şifa sürecinin içindesin.",
     "reversed": "Umutsuzluk, ilham kaybı, inançsızlık, şifayı reddetme."},
    {"id": 18, "suit": "major", "name": "The Moon",           "tr": "Ay",              "icon": "🌕",
     "element": "Su", "planet": "Balık",
     "keywords": "yanılsamalar, korkular, bilinçaltı, belirsizlik, sezgi",
     "upright":  "Gözle görülenden fazlası var. Yanılsamalar ve korkular seni yönlendiriyor olabilir.",
     "reversed": "Yanılsamaların dağılması, bilinçaltının aydınlanması, korkuların çözülmesi."},
    {"id": 19, "suit": "major", "name": "The Sun",            "tr": "Güneş",           "icon": "☀️",
     "element": "Ateş", "planet": "Güneş",
     "keywords": "sevinç, başarı, aydınlanma, vitalite, berraklık",
     "upright":  "En parlak kartlardan biri. Sevinç, başarı ve netlik dönemi. Işığa çık.",
     "reversed": "Geçici bulutlanma, aşırı iyimserlik, ego şişmesi."},
    {"id": 20, "suit": "major", "name": "Judgement",          "tr": "Yargı",           "icon": "📯",
     "element": "Ateş", "planet": "Plüton",
     "keywords": "uyanış, yenilenme, hesaplaşma, çağrı, dönüşüm",
     "upright":  "Büyük bir uyanış çağrısı. Geçmişle hesaplaş, affet ve yüksel.",
     "reversed": "Kendini yargılama, geçmişte takılı kalma, çağrıyı görmezden gelme."},
    {"id": 21, "suit": "major", "name": "The World",          "tr": "Dünya",           "icon": "🌍",
     "element": "Toprak", "planet": "Satürn",
     "keywords": "tamamlanma, entegrasyon, zafer, bütünlük, döngünün sonu",
     "upright":  "Bir döngü tamamlandı. Kutla. Bütün parçalar bir araya geldi.",
     "reversed": "Tamamlanmamış iş, başarının gecikmesi, kapanış olmadan ilerleme."},
]

# ── MINOR ARCANA — YARDIMCI FONKSİYON ─────────────────────────
def _minor(num, suit, tr_suit, name, tr_name, icon, element, keywords, upright, reversed_):
    return {
        "id": f"{suit}_{num}",
        "suit": suit,
        "suit_tr": tr_suit,
        "name": name,
        "tr": tr_name,
        "icon": icon,
        "element": element,
        "keywords": keywords,
        "upright": upright,
        "reversed": reversed_,
    }

# ── DEĞNEKLER (WANDS) — Ateş elementi, 14 kart ───────────────
WANDS = [
    _minor("ace",  "wands","Değnekler","Ace of Wands",   "DeğnekAsı",    "🔥","Ateş",
           "ilham, yeni girişim, yaratıcı enerji, potansiyel",
           "Büyük bir ilham kıvılcımı. Başla. Enerji yüksek.",
           "Gecikme, motivasyon eksikliği, fırsatın kaçırılması."),
    _minor("2",    "wands","Değnekler","Two of Wands",    "İki Değnek",    "🌐","Ateş",
           "planlama, vizyon, ufuk, ilerleme kararı",
           "Dünyayı elinde tutuyorsun. Bir sonraki adımı planla.",
           "Korku, belirsizlik, sınırlı vizyon."),
    _minor("3",    "wands","Değnekler","Three of Wands",  "Üç Değnek",     "⛵","Ateş",
           "genişleme, beklenti, fırsatlar, uzak ufuklar",
           "Emeklerin meyvesi yakın. Gemiler dönüyor.",
           "Gecikmeler, hayal kırıklığı, işlerin yolunda gitmemesi."),
    _minor("4",    "wands","Değnekler","Four of Wands",   "Dört Değnek",   "🎊","Ateş",
           "kutlama, uyum, istikrar, ev, başarı",
           "Kutla! Bir şey tamamlandı. Güvenli liman.",
           "Uyumsuzluk, gecikmiş kutlama, istikrarsızlık."),
    _minor("5",    "wands","Değnekler","Five of Wands",   "Beş Değnek",    "⚔️","Ateş",
           "çatışma, rekabet, mücadele, kaos, farklı görüşler",
           "Rekabet ve çatışma var. Enerjiyi doğru yönlendir.",
           "Çatışmadan kaçınma, iç çatışma, gereksiz mücadele."),
    _minor("6",    "wands","Değnekler","Six of Wands",    "Altı Değnek",   "🏆","Ateş",
           "zafer, tanınma, başarı, liderlik, onay",
           "Kazandın. Başarın tanınıyor. Öne çık.",
           "Ego, başarısızlık korkusu, onay bağımlılığı."),
    _minor("7",    "wands","Değnekler","Seven of Wands",  "Yedi Değnek",   "🛡️","Ateş",
           "savunma, dayanıklılık, rekabete karşı duruş, kararlılık",
           "Konumunu koru. Meydan okumalar var ama sen üsttesin.",
           "Bunalmışlık, teslim olma, savunmacılık."),
    _minor("8",    "wands","Değnekler","Eight of Wands",  "Sekiz Değnek",  "💨","Ateş",
           "hız, hareket, hızlı gelişmeler, iletişim, seyahat",
           "Her şey hızlanıyor. Hazır ol — haberler ve değişimler geliyor.",
           "Gecikme, engeller, sinyal kaybı, aceleci kararlar."),
    _minor("9",    "wands","Değnekler","Nine of Wands",   "Dokuz Değnek",  "🏴","Ateş",
           "dayanıklılık, son hamle, yorgunluk, bitmek üzere",
           "Neredeyse bitti. Son bir hamle daha. Bırakma.",
           "Tükenme, paranoya, aşırı savunmacılık."),
    _minor("10",   "wands","Değnekler","Ten of Wands",    "On Değnek",     "🎒","Ateş",
           "ağır yük, sorumluluk, tükenme, zorla taşıma",
           "Fazla yüklendin. Devretme ya da bırakma zamanı.",
           "Yükten kurtulma, sorumluluktan kaçınma."),
    _minor("page", "wands","Değnekler","Page of Wands",   "Değnek Valesi", "🌱","Ateş",
           "merak, keşif, coşkulu başlangıç, öğrenme arzusu",
           "Yeni fikirlere açık, meraklı enerji. Keşfet.",
           "Dağınıklık, heyecansızlık, olgunlaşmamış fikirler."),
    _minor("knight","wands","Değnekler","Knight of Wands", "Değnek Şövalyesi","🐎","Ateş",
           "macera, ateş, atılganlık, risk, karizmatik enerji",
           "Cesaretli ve kararlı ilerleme. Ateşin gücüyle hareket et.",
           "Düşüncesizlik, enerji dağınıklığı, sabırsızlık."),
    _minor("queen","wands","Değnekler","Queen of Wands",  "Değnek Kraliçesi","🦁","Ateş",
           "karizmatik liderlik, özgüven, yaratıcılık, ısı",
           "Kendin ol. Sahneye çık. Doğuştan gelen gücün var.",
           "İçe kapanma, güvensizlik, kontrol kaybı."),
    _minor("king", "wands","Değnekler","King of Wands",   "Değnek Kralı",  "👑","Ateş",
           "vizyon, liderlik, girişimcilik, ilham, güç",
           "Vizyoner lider arketipi. Büyük resmi gör ve yönlendir.",
           "Baskıcı liderlik, egoist güç, aceleci kararlar."),
]

# ── KUPALAR (CUPS) — Su elementi, 14 kart ─────────────────────
CUPS = [
    _minor("ace",  "cups","Kupalar","Ace of Cups",    "Kupa Ası",       "💧","Su",
           "yeni aşk, duygusal açılım, sezgi, bereket",
           "Kalp açılıyor. Yeni bir duygu, ilişki ya da yaratıcı ilham.",
           "Bastırılmış duygular, duygusal blok, reddedilen sevgi."),
    _minor("2",    "cups","Kupalar","Two of Cups",     "İki Kupa",       "🤝","Su",
           "birlik, karşılıklı çekim, ortaklık, bağlanma",
           "Güçlü bir bağ kuruldu. Karşılıklı çekim ve uyum.",
           "Uyumsuzluk, ilişki kırılması, dengesiz bağ."),
    _minor("3",    "cups","Kupalar","Three of Cups",   "Üç Kupa",        "🥂","Su",
           "kutlama, dostluk, topluluk, sevinç, işbirliği",
           "Arkadaşlarla kutla. Neşe ve birliktelik zamanı.",
           "Dedikodu, gruba bağımlılık, aşırı eğlence."),
    _minor("4",    "cups","Kupalar","Four of Cups",    "Dört Kupa",      "😶","Su",
           "içe kapanma, değerlendirme, memnuniyetsizlik, fırsat",
           "Önündeki fırsatı görmüyor olabilirsin. Başını kaldır.",
           "Fırsatı yakalama, yeni bakış açısı, geri dönüş."),
    _minor("5",    "cups","Kupalar","Five of Cups",    "Beş Kupa",       "😢","Su",
           "kayıp, üzüntü, pişmanlık, yas, dersler",
           "Kaybettiğine odaklanıyorsun. Ama hâlâ ayakta olanlar var.",
           "Kabul, iyileşme, geçmişi bırakma."),
    _minor("6",    "cups","Kupalar","Six of Cups",     "Altı Kupa",      "🌸","Su",
           "nostalji, geçmiş, masumiyet, hatıralar, hediye",
           "Geçmişten gelen bir şey. Masum anların özlemi.",
           "Geçmişte takılı kalma, olgunlaşmamış duygular."),
    _minor("7",    "cups","Kupalar","Seven of Cups",   "Yedi Kupa",      "✨","Su",
           "hayal, yanılsama, seçenekler, fantezi, berraklık eksikliği",
           "Çok seçenek var. Hangisi gerçek? Yanılsamalardan sıyrıl.",
           "Netlik kazanma, hayalden gerçeğe adım."),
    _minor("8",    "cups","Kupalar","Eight of Cups",   "Sekiz Kupa",     "🚶","Su",
           "terk etme, arayış, ruhsal yolculuk, ilerleme",
           "Yeterince iyi olan şeyi bırakıp daha iyisini arama cesareti.",
           "Korku, bırakamama, boşluğa dönüş."),
    _minor("9",    "cups","Kupalar","Nine of Cups",    "Dokuz Kupa",     "🌟","Su",
           "dilek gerçekleşiyor, memnuniyet, başarı, mutluluk",
           "Dilek kartı. İstediğin geliyor. Nimetleri say.",
           "Şımarıklık, yüzeysel memnuniyet, maddi odaklanma."),
    _minor("10",   "cups","Kupalar","Ten of Cups",     "On Kupa",        "🌈","Su",
           "mutlu son, aile uyumu, tatmin, huzur, duygusal bütünlük",
           "Duygusal açıdan en güzel kart. Huzur ve birliktelik.",
           "Aile uyumsuzluğu, kırık rüyalar, yüzeysel mutluluk."),
    _minor("page", "cups","Kupalar","Page of Cups",    "Kupa Valesi",    "🐟","Su",
           "yaratıcı mesaj, sezgili keşif, duygusal açıklık",
           "Beklenmedik bir mesaj ya da sezgi. Açık kal.",
           "Duygusal olgunlaşmamışlık, hayal kırıklığı."),
    _minor("knight","cups","Kupalar","Knight of Cups", "Kupa Şövalyesi", "💌","Su",
           "romantik teklif, idealist, şiirsel ruh, davet",
           "Romantik ya da yaratıcı bir davet geliyor.",
           "Hayal kırıklığı, gerçekçi olmayan beklentiler, duygusal manipülasyon."),
    _minor("queen","cups","Kupalar","Queen of Cups",   "Kupa Kraliçesi", "🫧","Su",
           "şefkat, sezgi, duygusal zeka, empati, şifa",
           "Derin sezgi ve şefkat. Kalbinle bil.",
           "Duygusal manipülasyon, aşırı hassasiyet, öz ihmal."),
    _minor("king", "cups","Kupalar","King of Cups",    "Kupa Kralı",     "🌊","Su",
           "duygusal olgunluk, denge, bilge lider, şifa",
           "Duyguların patronu. Empatiyle liderlik.",
           "Duygusal soğukluk, bastırma, manipülasyon."),
]

# ── KILIÇLAR (SWORDS) — Hava elementi, 14 kart ───────────────
SWORDS = [
    _minor("ace",  "swords","Kılıçlar","Ace of Swords",   "Kılıç Ası",     "⚔️","Hava",
           "netlik, hakikat, zeka, keskinlik, yeni fikir",
           "Zihnin berraklaşıyor. Hakikat kesiyor ama özgürleştirir.",
           "Kaos, kafa karışıklığı, yanlış anlama."),
    _minor("2",    "swords","Kılıçlar","Two of Swords",    "İki Kılıç",     "🙈","Hava",
           "karar verememe, körlük, çıkmaz, denge",
           "Gözlerini kapat ve içini dinle. Bildiğini biliyorsun.",
           "Gerilimin çözülmesi, karar verme, bilgiye ulaşma."),
    _minor("3",    "swords","Kılıçlar","Three of Swords",  "Üç Kılıç",      "💔","Hava",
           "kalp kırıklığı, acı, üzüntü, ihanet, gerçek",
           "Acı gerçek. Yas tut, ama bu da geçecek.",
           "Acıdan iyileşme, affetme, kalp onarımı."),
    _minor("4",    "swords","Kılıçlar","Four of Swords",   "Dört Kılıç",    "😴","Hava",
           "dinlenme, iyileşme, geri çekilme, meditasyon",
           "Dur. Zihnin ve bedenin dinlenmeye ihtiyaç duyuyor.",
           "Hareketsizlik, tükenmişlik, yeniden aktive olma."),
    _minor("5",    "swords","Kılıçlar","Five of Swords",   "Beş Kılıç",     "😈","Hava",
           "çatışma, yenilgi, haksız kazanç, gurur",
           "Her savaşı kazanmak zorunda değilsin. Ne pahasına?",
           "Uzlaşma, kayıptan öğrenme, gururu bırakma."),
    _minor("6",    "swords","Kılıçlar","Six of Swords",    "Altı Kılıç",    "⛵","Hava",
           "geçiş, uzaklaşma, sakinleşme, ileriye doğru hareket",
           "Huzursuz sulardan sakin sulara doğru. Geçiş zamanı.",
           "Direnç, çözümsüz durum, geçmişe bağlılık."),
    _minor("7",    "swords","Kılıçlar","Seven of Swords",  "Yedi Kılıç",    "🦊","Hava",
           "strateji, hile, bağımsız hareket, gizli plan",
           "Akıllıca ve dikkatli hareket et. Herkes bilmemeli.",
           "Aldatmanın ortaya çıkması, vicdanın uyanması."),
    _minor("8",    "swords","Kılıçlar","Eight of Swords",  "Sekiz Kılıç",   "🔒","Hava",
           "kısıtlama, kendi kendine hapsetme, güçsüzlük hissi",
           "Zincirler aslında daha gevşek. Zihin seni hapsediyor.",
           "Özgürleşme, kısıtlamanın farkındalığı, yeni perspektif."),
    _minor("9",    "swords","Kılıçlar","Nine of Swords",   "Dokuz Kılıç",   "😰","Hava",
           "kaygı, kabus, aşırı düşünme, gece korkuları",
           "En kötü senaryo kafanda. Gerçekte bu kadar kötü değil.",
           "Durumun iyileşmesi, korkunun azalması, yardım almak."),
    _minor("10",   "swords","Kılıçlar","Ten of Swords",    "On Kılıç",      "🌅","Hava",
           "son, yenilgi, kriz noktası, ama şafak",
           "En dip nokta. Bundan sonra yukarı çıkar. Sabah olacak.",
           "Hayatta kalma, iyileşme, trajediyi abartma."),
    _minor("page", "swords","Kılıçlar","Page of Swords",   "Kılıç Valesi",  "🔍","Hava",
           "merak, bilgi arayışı, dikkatli gözlem, haber",
           "Gözle, araştır, soru sor. Haberler geliyor.",
           "Dedikodu, yetersiz bilgi, dağınık zihin."),
    _minor("knight","swords","Kılıçlar","Knight of Swords","Kılıç Şövalyesi","🌪️","Hava",
           "hız, kararlılık, aksiyon, zihinsel keskinlik",
           "Tam hızla ilerle. Kararını verdin — git.",
           "Düşüncesizlik, agresif iletişim, körü körüne ilerleme."),
    _minor("queen","swords","Kılıçlar","Queen of Swords",  "Kılıç Kraliçesi","🗡️","Hava",
           "bağımsızlık, doğrudan iletişim, keskin zeka, sınırlar",
           "Sınırlarını koy. Berrak, dürüst ve keskin ol.",
           "Soğukluk, zalimlik, aşırı eleştirel tutum."),
    _minor("king", "swords","Kılıçlar","King of Swords",   "Kılıç Kralı",   "👁️","Hava",
           "otorite, mantık, etik liderlik, adil yargı",
           "Mantık ve adaletle liderlik et. Nesnel kal.",
           "Manipülatif güç, duygusuz yargı, tirani."),
]

# ── TILSIMLAR (PENTACLES) — Toprak elementi, 14 kart ──────────
PENTACLES = [
    _minor("ace",  "pentacles","Tılsımlar","Ace of Pentacles",   "Tılsım Ası",       "💰","Toprak",
           "maddi fırsat, bereket, yeni kaynak, temeller",
           "Maddi ya da finansal yeni başlangıç. Toprak al.",
           "Kaçırılan fırsat, maddi güvensizlik."),
    _minor("2",    "pentacles","Tılsımlar","Two of Pentacles",    "İki Tılsım",       "⚖️","Toprak",
           "denge, çoklu görev, esneklik, önceliklendirme",
           "Dengeyi koru. Birden fazla şeyi yönetiyorsun.",
           "Denge kaybı, aşırı yüklenme, finansal dengesizlik."),
    _minor("3",    "pentacles","Tılsımlar","Three of Pentacles",  "Üç Tılsım",        "🏗️","Toprak",
           "işbirliği, ustalık, ekip çalışması, planlama",
           "Birlikte daha güçlüsünüz. Uzman ekip kuruldu.",
           "Uyumsuz çalışma, beceri eksikliği, iletişim sorunları."),
    _minor("4",    "pentacles","Tılsımlar","Four of Pentacles",   "Dört Tılsım",      "🤑","Toprak",
           "biriktirme, kontrol, güvenlik, cimrilik",
           "Güvende hissediyorsun. Ama tutmak bazen kaybettirir.",
           "Açılma, cimriliği bırakma, kayıp korkusu."),
    _minor("5",    "pentacles","Tılsımlar","Five of Pentacles",   "Beş Tılsım",       "❄️","Toprak",
           "maddi zorluk, yoksunluk, izolasyon, ama yardım mevcut",
           "Zor bir dönem. Ama kilisedeki ışık yanıyor — yardım yakın.",
           "Maddi iyileşme, yardım almak, şükran."),
    _minor("6",    "pentacles","Tılsımlar","Six of Pentacles",    "Altı Tılsım",      "🤲","Toprak",
           "cömertlik, denge, verme-alma, kaynak paylaşımı",
           "Ver ya da al — iki yönde de denge var. Bolluk akıyor.",
           "Borç, eşitsiz paylaşım, koşullu cömertlik."),
    _minor("7",    "pentacles","Tılsımlar","Seven of Pentacles",  "Yedi Tılsım",      "🌱","Toprak",
           "sabır, yatırım, bekleme, değerlendirme, uzun vade",
           "Ektiklerini suluyorsun. Sabır. Hasat gelecek.",
           "Sabırsızlık, yatırımdan cayma, kısa vadeli düşünce."),
    _minor("8",    "pentacles","Tılsımlar","Eight of Pentacles",  "Sekiz Tılsım",     "⚒️","Toprak",
           "ustalık, özveri, öğrenme, pratik çalışma, zanaatkarlık",
           "Çalış, pratik yap, ustalığa eriş. Süreç seni dönüştürür.",
           "Mükemmeliyetçilik, kalite eksikliği, motivasyon kaybı."),
    _minor("9",    "pentacles","Tılsımlar","Nine of Pentacles",   "Dokuz Tılsım",     "🦅","Toprak",
           "bağımsızlık, lüks, öz yeterlilik, kazanılmış başarı",
           "Kendi başarınla bağımsız. Bunu sen hak ettin.",
           "Maddi bağımlılık, sahte lüks, yalnızlık."),
    _minor("10",   "pentacles","Tılsımlar","Ten of Pentacles",    "On Tılsım",        "🏰","Toprak",
           "kalıcı başarı, aile mirası, servet, uzun vadeli güvenlik",
           "Kalıcı bir şey inşa ettin. Nesiller arası miras.",
           "Aile çatışması, maddi baskı, mirasa bağlılık."),
    _minor("page", "pentacles","Tılsımlar","Page of Pentacles",   "Tılsım Valesi",    "📚","Toprak",
           "öğrenme, pratik beceri, fırsat araştırma, yeni proje",
           "Yeni bir pratik beceri öğrenme ya da proje zamanı.",
           "Dağınıklık, hayal kurmak ama uygulamamak."),
    _minor("knight","pentacles","Tılsımlar","Knight of Pentacles","Tılsım Şövalyesi", "🐂","Toprak",
           "güvenilirlik, sabır, metodoloji, istikrar",
           "Yavaş ama emin adımlar. Kaliteli ve güvenilir iş.",
           "Durgunluk, değişime direnç, aşırı temkinlilik."),
    _minor("queen","pentacles","Tılsımlar","Queen of Pentacles",  "Tılsım Kraliçesi", "🌿","Toprak",
           "pratik şefkat, bolluk, doğa, güvenli yuva, öz bakım",
           "Besleyici ve pratik güç. Hem ver hem kendini koru.",
           "İş-yaşam dengesizliği, maddi obsesyon, ihmal."),
    _minor("king", "pentacles","Tılsımlar","King of Pentacles",   "Tılsım Kralı",     "🏛️","Toprak",
           "maddi başarı, güvenilir lider, zenginlik, istikrar",
           "Pratik zeka ve istikrarla liderlik. Maddi güç zirvede.",
           "Maddi obsesyon, yolsuzluk, katılık."),
]

# ── TAM DESTE — 78 KART ───────────────────────────────────────
FULL_DECK = MAJOR_ARCANA + WANDS + CUPS + SWORDS + PENTACLES

def get_deck_stats():
    return {
        "total": len(FULL_DECK),
        "major": len(MAJOR_ARCANA),
        "wands": len(WANDS),
        "cups":  len(CUPS),
        "swords":len(SWORDS),
        "pentacles": len(PENTACLES),
    }

if __name__ == "__main__":
    stats = get_deck_stats()
    print(f"Tam deste: {stats}")
    assert stats["total"] == 78, f"78 kart olmalı, {stats['total']} var!"
    print("✅ 78 kart doğrulandı")
